global_exclude_dirs:
    - translations
    - upgrade

exclude_patterns:
    - tools/debug.php

rules:
    php.absolute_path_present:
        enabled: true
        allowed_paths: []
    php.method_too_long:
        enabled: true
        max_length: 50
        threshold: 15
    php.psr1:
        enabled: false
